= Parameters

Because this component depends on the component https://hub.syn.tools/appuio-cloud-reporting/references/parameters.html[appuio-cloud-reporting], some parameters are taken from that component and are not individually configurable in this component.
In particular:

* https://hub.syn.tools/appuio-cloud-reporting/references/parameters.html#_namespace[namespace]
* https://hub.syn.tools/appuio-cloud-reporting/references/parameters.html#_database[database]

The following list includes only parameters of this component.
The parent key for all of them is `exoscale_metrics_collector`.

See xref:how-tos/installation.adoc[Installation] for a full example.

== `images`

[horizontal]
type:: dictionary
default:: https://github.com/vshn/exoscale-metrics-collector/blob/master/component/class/defaults.yml[See class/defaults.yml].

Dictionary containing the container images used by this component.

== `schedule`

[horizontal]
type:: string
default:: `10 10,16,20 * * *`

The cron schedule at which the metrics collection job is spawned.

== `secrets.credentials.stringData.EXOSCALE_API_KEY`

[horizontal]
type:: string
default:: Required.

The Exoscale API key.

You need to get the token from the https://portal.exoscale.com[Exoscale Console].
You need to select the correct account (token is limited to one account), choose "IAM" in the menu and generate a new key pair.

== `secrets.credentials.stringData.EXOSCALE_API_SECRET`

[horizontal]
type:: string
default:: Required.

The Exoscale API secret.

Second part of the Exoscale API credentials.
See EXOSCALE_API_KEY for instructions.

== `secrets.credentials.stringData.K8S_SERVER_URL`

[horizontal]
type:: string
default:: Required.

The Kubernetes server URL.

== `secrets.credentials.stringData.K8S_TOKEN`

[horizontal]
type:: string
default:: Required.

The token to connect to a Kubernetes cluster.

The Service Account connected to this token should have `get` and `list` permissions to the following managed resources:

* `buckets.exoscale.crossplane.io`
* `postgresqls.exoscale.crossplane.io`

== `secrets.credentials.stringData.ACR_DB_URL`

[horizontal]
type:: string
default:: Required.

The Billing Database URL.
