= Installation

== Requirements

This component requires https://github.com/appuio/component-appuio-cloud-reporting[component-appuio-cloud-reporting] and is installed into the same namespace.
This is required for this component to be able to access the billing database and its connection secrets.
It also requires an Exoscale IAMKey and a Kubernetes/OpenShift Service Account token in the target cluster to get resources (e.g. SOS buckets, Postgres, etc).

== Sources

The data is matched from a k8s cluster and an Exoscale organization.
The Kubernetes Service Account token is required to have `get` permissions on `Namespaces` and to the following managed resources:

* `buckets.exoscale.crossplane.io`
* `postgresqls.exoscale.crossplane.io`
* `mysqls.exoscale.crossplane.io`
* `redis.exoscale.crossplane.io`
* `kafkas.exoscale.crossplane.io`
* `opensearches.exoscale.crossplane.io`

=== Exoscale organization
The Access Key (IAM Key) from an Exoscale organization is required to have read access across all managed resources (e.g. SOS buckets, Postgres, etc).

=== K8s cluster
The access to the desired cluster from where the metrics should be collected has to be configured. The current configuration for each instance is done in the
`syn-tenant-repo` under `manifests/<desired-cluster>/billing`

== Example

[source,yaml]
----
applications:
  - metrics-collector

parameters:
  metrics_collector:
    exoscale:
      enabled: true
      objectStorage:
        schedule: '10 10,16,20 * * *'
      dbaas:
        enabled: true # must be manually enabled to scrape DBaas metrics
        schedule: '*/15 * * * *'
----

See the xref:references/parameters.adoc[parameters] reference for a full list of parameters.
